### ISSUE TITLE
Test mode could log information to console

### ISSUE THREAD

**Issue by pluby** [NewRedo/sagepay-server#3]
It would be useful to spit out the transaction information to the console when running in test mode. Otherwise, applications being developed will not be able to verify that they are charging the right amount and passing other important details in the transaction.

Current logging that says "Simulation" should probably be clearer, maybe say "sagepay-server: (test mode)" as the prefix.

Note this is not to be confused with the example that spits things out to the console all the time. Its the test mode in the Express module.

**Comment by pluby** [comment]
@midgleyc Is this worth addressing while you're at it?

**Comment by midgleyc** [comment]
Fixed in 81d52787f31b37602587d63d2b2d046666b16764
